config/routes.rb
Rails.application.routes.draw do
  # get 'admin/index'

  # privacy page
  get "privacy", to: "privacy#index", as: :privacy

  # Post action for the contact form in landing controller
  post "/landing/lead", to: "landing#create_lead", as: :create_lead
  # Post action for the newsletter form in landing controller
  post "/landing/newsletter", to: "landing#create_newsletter", as: :create_newsletter

  # Root route for advisor
  authenticated :admin, lambda { |a| a.role == "advisor" } do
    root to: "advisor#index", as: :advisor
  end

   # Root route for admin
   authenticated :admin, lambda { |a| a.role == "admin" } do
    root to: "admin#index", as: :admin
  end
  # Update action for update note for lead through admin dashboard
  patch "update_lead/:id", to: "admin#update_lead", as: :admin_update_lead
  # Delete action for the destroy lead
  delete "destroy_lead/:id", to: "admin#destroy_lead", as: :admin_destroy_lead
  # Delete action for the destroy newsletter
  delete "destroy_newsletter/:id", to: "admin#destroy_newsletter", as: :admin_destroy_newsletter

  # get the blog general root
  get "blog", to: "blog#index", as: :blog
  # get the single blog - show
  get "/blog/:id", to: "blog#show", as: :blog_show

  # Route for new blog
  get "new_blog", to: "advisor#new_blog", as: :advisor_new_blog
  # Route for list of blogs
  get "list_blogs", to: "advisor#list_blogs", as: :advisor_list_blogs
  # Route for edit blog
  get "edit_blog/:id", to: "advisor#edit_blog", as: :advisor_edit_blog
  # create blog through advisor dashboard
  post "create_blog", to: "advisor#create_blog", as: :advisor_create_blog
  # update blog through advisor dashboard
  patch "update_blog/:id", to: "advisor#update_blog", as: :advisor_update_blog
  # delete blog through advisor dashboard
  delete "destroy_blog/:id", to: "advisor#destroy_blog", as: :advisor_destroy_blog
  # delete cover image through advisor dashboard
  resources :blog do
    resources :cover_images, only: [:destroy], module: :blog
  end

  devise_for :admins, controllers: {
    sessions: "admin/sessions"
  }
  root 'landing#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  # GET /landings
  def index
    @top_blogs = Blog.published.includes(
      [:admin, :rich_text_content, cover_image_attachment: { blob: [] }]
      ).order(views: :desc).limit(2)
  end

  # POST /landing/newsletter
  # Create a newsletter from the landing page
  def create_newsletter
    @newsletter = Newsletter.new(newsletter_params)

    if newsletter_params[:pp_check] == "0" || newsletter_params[:pp_check] == false
      redirect_to root_path, alert: "Please check the privacy policy"
    else
      respond_to do |format|
        if @newsletter.save
          # Send email to driver
          NewsletterMailer.new_newsletter_email(@newsletter).deliver_now
          format.html { redirect_to root_path, notice: "Thank you for signing up!" }
        else
          format.html { redirect_to root_path, alert: "Failed to sign up: #{@newsletter.errors.full_messages.join(', ')}" }
        end
      end
    end
  end

    # POST /landing/lead
    # # Create a lead from the landing page
    def create_lead
      @lead = Lead.new(lead_params)

      if lead_params[:pp_check] == "0" || lead_params[:pp_check] == false
        redirect_to root_path, alert: "Please check the privacy policy"
      else
        respond_to do |format|
          if @lead.save
            # Create a new user using the email field from the landing form
            #User.create(email: params[:landing][:email], password: params[:landing][:last_name])

            # Send an email to the admin
            LeadMailer.new_lead_email(@lead).deliver_now

            # Send an thank you email to the driver
            DriverMailer.new_driver_email(@lead).deliver_now

            format.html { redirect_to root_path, notice: "We will reach out soon! Be sure to check your email" }
          else
            format.html { redirect_to root_path, alert: "Failed to sign up: #{@lead.errors.full_messages.join(', ')}" }
          end
        end
      end
    end

    private

    # Never trust parameters from the scary internet, only allow the white list through.
    # This is especially important for the form that is publicly accessible.
    def lead_params
      params.require(:lead).permit(:first_name,
                                   :last_name,
                                   :email,
                                   :phone,
                                   :city,
                                   :state,
                                   :pp_check)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # This is especially important for the form that is publicly accessible.
    def newsletter_params
      params.require(:newsletter).permit( :email, :pp_check)
    end
end

app/helpers/landing_helper.rb
module LandingHelper
  # require 'net/http'
  # In your controller or helper
# def background_image_style
#   image_url = 'https://truckerjobs.s3.us-east-2.amazonaws.com/truck_hyper_drive.jpg'
#   if image_exists?(image_url)
#     "url('#{image_url}')"
#   else
#     ''
#   end
# end

# def image_exists?(url)
#   uri = URI(url)
#   Net::HTTP.start(uri.host, uri.port, use_ssl: uri.scheme == 'https') do |http|
#     response = http.head(uri.path)
#     response.code == '200'
#   end
# end

end

app/views/landing/_leadform.html.erb
<%= form_with scope: :lead, url: create_lead_path, method: "post", class: "max-w-sm mx-auto" do |f| %>
  <div class="flex flex-col sm:flex-row w-full">
    <div class="mb-5 text-start mr-1">
      <div class="flex">
        <%= f.label :first_name, "First Name", for: "first_name", class: "block mb-2 text-sm font-medium text-white" %>
        <span class="text-orange-300 pl-2">*</span>
      </div>
      <%= f.text_field :first_name, id: "first_name", placeholder: "John", autocomplete: "off", class: " border text-sm rounded-lg block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500" %>
    </div>
    <div class="mb-5 text-start ml-1">
      <div class="flex">
        <%= f.label :last_name, "Last Name", for: "last_name", class: "block mb-2 text-sm font-medium text-white" %>
        <span class="text-orange-300 pl-2">*</span>
      </div>
      <%= f.text_field :last_name, id: "last_name", placeholder: "Smith", autocomplete: "off", class: " border text-sm rounded-lg block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500" %>
    </div>
  </div>
  <div class="mb-5 text-start">
    <div class="flex">
      <%= f.label :lead_email, "Email", for: "lead_email", class: "block mb-2 text-sm font-medium text-white" %>
      <span class="text-orange-300 pl-2">*</span>
    </div>
    <%= f.email_field :email, id: "lead_email", placeholder: "name@example.com", autocomplete: "off", class: " border text-sm rounded-lg block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500" %>
  </div>
  <div class="mb-5 text-start">
    <div class="flex">
      <%= f.label :phone, "Phone", for: "phone", class: "block mb-2 text-sm font-medium text-white" %>
      <span class="text-orange-300 pl-2">*</span>
    </div>
    <%= f.text_field :phone, id: "phone", placeholder: "555 888 1234", autocomplete: "off", class: " border text-sm rounded-lg block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500" %>
  </div>
  <div class="mb-5 text-start">
    <div class="flex">
      <%= f.label :city, "City", for: "city", class: "block mb-2 text-sm font-medium text-white" %>
      <span class="text-orange-300 pl-2">*</span>
    </div>
    <%= f.text_field :city, id: "city", placeholder: "Chicago", autocomplete: "off", class: " border text-sm rounded-lg block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500" %>
  </div>
  <div class="mb-5 text-start">
    <div class="flex">
      <%= f.label :state, "State", for: "state", class: "block mb-2 text-sm font-medium text-white" %>
      <span class="text-orange-300 pl-2">*</span>
    </div>
    <%= f.text_field :state, id: "state", placeholder: "IL", autocomplete: "off", class: " border text-sm rounded-lg block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500" %>
  </div>
  <div class="mx-auto max-w-screen-sm text-xs text-left text-gray-300">
    <%= f.check_box :pp_check, checked: true, 'aria-label' => "privacy policy"  %>&nbsp; I agree with the
    <%= link_to "Privacy Policy", privacy_path, class: "font-medium text-blue-300 hover:underline" %>.
  </div>
  <div class="text-xs text-orange-300 text-left pt-2">* Must agree to privacy policy for services *</div>
  <%= f.submit "Send", class: "text-white focus:ring-4 focus:outline-none font-medium rounded-lg text-sm w-full sm:w-auto mt-4 px-8 py-3 text-center bg-blue-600 hover:bg-blue-700 focus:ring-blue-800 cursor-pointer" %>
<% end %>

app/views/landing/_newsletter.html.erb
<%= form_with scope: :newsletter, url: create_newsletter_path, class: "max-w-sm mx-auto" do |f| %>
  <div class="items-center mx-auto mb-3 space-y-4 max-w-screen-sm sm:flex sm:space-y-0">
    <div class="relative w-full">
      <label for="email_news" class="hidden mb-2 text-sm font-medium text-gray-300">Email address</label>
      <div class="flex absolute inset-y-0 left-0 items-center pl-3 pointer-events-none">
        <svg class="w-5 h-5 text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M2.003 5.884L10 9.882l7.997-3.998A2 2 0 0016 4H4a2 2 0 00-1.997 1.884z"></path><path d="M18 8.118l-8 4-8-4V14a2 2 0 002 2h12a2 2 0 002-2V8.118z"></path></svg>
      </div>
      <%= f.email_field :email, id: "email_news", placeholder: "Enter your email", autocomplete: "off", class: "block py-3 pl-10 w-full text-sm rounded-lg border sm:rounded-none sm:rounded-l-lg bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-primary-500 focus:border-primary-500" %>
    </div>
    <div>
      <%= f.submit "Subscribe", class: "text-white py-3 px-6 w-full text-sm font-medium text-center rounded-lg border cursor-pointer sm:rounded-none sm:rounded-r-lg bg-primary-600 hover:bg-primary-700 focus:ring-primary-800" %>
    </div>
  </div>
  <div class="mx-auto max-w-screen-sm text-xs text-left text-gray-300">
    <%= f.check_box :pp_check, checked: true, 'aria-label' => "privacy policy" %>&nbsp; I agree with the
    <%= link_to "Privacy Policy", privacy_path, class: "font-medium text-blue-300 hover:underline" %>
  </div>
  <div class="text-xs text-orange-300 text-left pt-1">
    * Must agree to privacy policy to recieve Newsletters *
  </div>
<% end %>

app/views/landing/index.html.erb
<!--hero-->
<section id="hero" class="mt-14 w-full min-h-svh bg-zinc-950 bg-no-repeat bg-center bg-cover bg-[url('https://truckerjobs.s3.us-east-2.amazonaws.com/truck_hyper_drive.jpg')]">
  <div class="flex justify-center items-center py-8 px-4 w-full min-h-svh lg:py-16 z-10 bg-gradient-to-br from-orange-400/40 via-teal-950/20 to-gray-500/30 relative">
    <div class="flex flex-col justify-center items-center lg:w-fit text-center md:mt-44 lg:mt-60 bg-slate-900/50 px-2 py-5 rounded-lg">
      <% if notice.present? %>
        <p class="py-2 px-3 bg-black mb-5 text-teal-400 text-base md:text-lg rounded-lg inline-block max-w-sm" id="notice"><%= notice %></p>
      <% end %>
      <% if alert.present? %>
        <p class="py-2 px-3 bg-black mb-5 text-rose-400 text-base md:text-lg rounded-lg inline-block max-w-sm" id="alert"><%= alert %></p>
      <% end %>
      <span class="mb-1 text-2xl font-semibold tracking-tight leading-none md:text-4xl lg:text-4xl text-white">
        Steer your career in the right direction.
      </span>
      <div class="flex flex-col justify-center items-center w-11/12">
        <%= image_tag('https://blog3169.s3.us-east-2.amazonaws.com/logo1.png', alt: "logo image in a military stencile style") %>
      </div>
      <%= link_to "START YOUR JOURNEY", "#contact", class: "py-6 px-12 mt-6 rounded bg-yellow-300 text-slate-900 hover:bg-yellow-400 cursor-pointer" %>
    </div>
  </div>
</section>
<!--newsletter-->
<section id="newsletter" class="w-full bg-gray-900">
  <div class="py-8 px-4 mx-auto max-w-screen-xl lg:py-16 lg:px-6 z-10 relative">
    <div class="mx-auto max-w-screen-md sm:text-center">
      <h2 class="mb-4 text-3xl tracking-tight font-extrabold sm:text-4xl text-yellow-300">Stay up to date with our newsletter</h2>
      <p class="mx-auto mb-8 max-w-2xl font-light md:mb-12 sm:text-xl text-gray-400">Transportation is changing. Sign up to get the latest news on developments!</p>
      <%= render "newsletter" %>
    </div>
  </div>
</section>
<!--about --->
<section id="about" class="w-full bg-zinc-950">
  <div class="flex flex-col justify-center items-center py-8 px-4 w-full">
    <div class="lg:w-5/6 text-center">
      <div class="flex justify-center text-2xl sm:text-3xl my-6 text-gray-400">
        <span class="font-sans">About &nbsp;</span>
        <%= image_tag("https://blog3169.s3.us-east-2.amazonaws.com/logo1.png", alt: "logo image in a military stencile style", class: "w-1/2 lg:w-1/4 object-contain", loading: "lazy") %>
      </div>
      <p class="font-normal sm:text-xl text-gray-400 my-6">
        Founded in 2024 by a group of experienced recruiting specialists, TruckerJobs4u.com emerged from a collective vision to revolutionize the truck driver recruitment industry. Our founders, having spent years navigating the complexities of driver placement, recognized a glaring need for a more personalized and honest approach to career planning for truck drivers.
      </p>
      <p class="font-normal sm:text-xl text-gray-400 my-6">
        At TruckerJobs4u.com, we believe that every driver’s journey is unique. Our mission is to provide tailored career plans that align with each driver’s specific skills, goals, and lifestyle preferences. Unlike traditional recruitment agencies that often prioritize filling positions over the individual needs of drivers, we focus on creating meaningful matches between drivers and carriers.
      </p>
      <p class="font-normal sm:text-xl text-gray-400 my-6">
        We work closely with a network of reputable carriers that offer diverse opportunities, from local routes to long-haul trips. Our commitment is to ensure that every driver we place is positioned for long-term success and satisfaction. We pride ourselves on our integrity and professionalism, striving to build lasting relationships with both our drivers and carrier partners
      </p>
      <p class="font-normal sm:text-xl text-gray-400 my-6">
        At TruckerJobs4u.com, we go beyond mere job placement. We provide comprehensive support throughout the entire career journey of our drivers, from initial consultation to career advancement. Our goal is to redefine what it means to work in the trucking industry by offering drivers true career paths that not only meet their immediate needs but also pave the way for future growth and fulfillment
      </p>
      <p class="font-normal sm:text-xl text-gray-400 my-6">
        Join us at TruckerJobs4u.com, where your career journey is our top priority.
      </p>
    </div>
  </div>
</section>
<section id="paths" class="flex justify-center items-center w-full">
  <!--Paths to choose-->
  <div class="w-full lg:max-w-4xl my-10 p-4 text-center border rounded-lg shadow sm:p-8 bg-gray-800 border-gray-700">
    <div class="flex justify-center items-center">
      <%= image_tag("https://blog3169.s3.us-east-2.amazonaws.com/logo1.png", alt: "logo image in a military stencile style", class: "max-w-96", loading: "lazy") %>
    </div>
    <p class="mb-5 text-base sm:text-lg text-gray-400">
      Which route would you prefer? <br/>
      Fill out a quick form, letting our recruiters know a bit about you and what you are looking for or have you found a job and are ready to get serious about seeing what's over the horizon?
    </p>
    <div class="md:grid-cols-3 items-center justify-center space-y-4 sm:flex sm:space-y-0 sm:space-x-4 rtl:space-x-reverse">
      <!--Inquiry Card-->
      <div class="md:w-1/3 md:max-h-[700px] border rounded-lg shadow bg-gray-800 border-gray-700">
        <%= image_tag("https://truckerjobs.s3.us-east-2.amazonaws.com/Sunset+Truck+Interior-min.jpg", width: "480", alt: "View of the truck driver seat at sunset.", class: "rounded-t-lg", loading: "lazy") %>
        <div class="p-5">
          <span class="mb-2 text-2xl font-bold tracking-tight text-white">Quick Inquiry</span>
          <p class="mb-3 font-normal text-gray-400">Just starting to look around for better opportunities? We can help?</p>
          <%= link_to "#contact", class: "inline-flex items-center px-6 py-3 text-sm font-medium text-center text-white rounded-lg focus:ring-4 focus:outline-none bg-blue-600 hover:bg-blue-700 focus:ring-blue-800" do %>
            Help Me
            <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
            </svg>
          <% end %>
        </div>
      </div>
      <!--Application Card-->
      <div class="md:w-1/3 md:max-h-[700px] border rounded-lg shadow bg-gray-800 border-gray-700">
        <%= image_tag("https://truckerjobs.s3.us-east-2.amazonaws.com/Sunset-Trucking-Scene-min.jpg", width: "480", alt: "White Kenworth with red stripes in yard under red evening sky.", class: "rounded-t-lg", loading: "lazy") %>
        <div class="p-5">
          <span class="mb-2 text-2xl font-bold tracking-tight text-white">Application</span>
          <p class="mb-3 font-normal text-gray-400">Have you been asked to fill out a application? Get yourself square here.</p>
          <%= link_to "https://intelliapp.driverapponline.com/c/truckerjobs4u", target: "_blank", class: "inline-flex items-center px-6 py-3 text-sm font-medium text-center text-white rounded-lg focus:ring-4 focus:outline-none bg-blue-600 hover:bg-blue-700 focus:ring-blue-800" do %>
            Let's Go!
            <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
            </svg>
          <% end %>
        </div>
      </div>
      <!--Job Search Card-->
      <div class="md:w-1/3 md:max-h-[700px] border rounded-lg shadow bg-gray-800 border-gray-700">
        <%= link_to root_path do %>
          <%= image_tag("https://truckerjobs.s3.us-east-2.amazonaws.com/Sunset+Truck+Lineup-min.jpg", width: "480", alt: "Trucks lined up at the wharehouse as the sun rises.", class: "rounded-t-lg", loading: "lazy") %>
          <div class="p-5">
            <span class="mb-2 text-2xl font-bold tracking-tight text-white">Job Search</span>
            <p class="mb-3 font-normal text-gray-400">Want to browse the jobs we are currently placeing driver for? Drive Safe.</p>
            <%= link_to "https://www.classadrivers.com/truck-driving-jobs/c-5606-truckerjobs4u", target: "_blank", class: "inline-flex items-center px-6 py-3 text-sm font-medium text-center text-white rounded-lg focus:ring-4 focus:outline-none bg-blue-600 hover:bg-blue-700 focus:ring-blue-800" do %>
              Find it!
              <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
              </svg>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>
<!--Show Blog Articles-->
<section id="general" class="flex justify-center items-center bg-gray-900">
  <div class="py-8 px-4 mx-auto max-w-screen-xl sm:py-16 lg:px-6">
    <div class="max-w-screen-md mb-8 lg:mb-16">
      <h2 class="mb-4 text-4xl tracking-tight font-extrabold text-white">Blogs on TRUCKERJOBS4U</h2>
      <p class="text-gray-500 sm:text-xl dark:text-gray-400">TRUCKERJOBS4U has one central theme. To free you from the stress of the job hunt. With TRUCKERJOBS4U you get a dedicated professional who's top priorty is to help you find the driving career you've worked so hard for.</p>
    </div>
    <div class="space-y-8 md:grid md:grid-cols-2 md:gap-12 md:space-y-0">
      <!--blog1-->
      <% @top_blogs&.each do |blog| %>
        <div class="max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
          <%= link_to blog_show_path(blog) do %>
            <% if blog.cover_image.present? %>
              <%= image_tag blog.cover_image, alt: "Blog Image", class: "rounded-t-lg", loading: "lazy" %>
            <% end %>
          <% end %>
          <div class="p-5">
            <%= link_to blog_show_path(blog) do %>
              <span class="mb-2 text-2xl font-bold tracking-tight text-white"><%= blog.title %></span>
              <div class="flex justify-between py-1 px-2">
                <div class="flex flex-col">
                  <span class="font-medium text-slate-400"><%= "Author: #{blog.admin.first_name} #{blog.admin.last_name}" %></span>
                  <span class="font-medium text-slate-400"><%= "Date: #{blog.created_at.to_date.inspect}" %></span>
                </div>
                <div>
                  <span class="text-slate-400"><%= pluralize(blog.views, "review") %></span>
                </div>
              </div>
            <% end %>
            <p class="mb-3 font-normal text-slate-400"><%= blog.content.to_plain_text.truncate_words(30) %></p>
            <%= link_to blog_show_path(blog), class: "inline-flex items-center px-6 py-3 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" do %>
              Review Article
              <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
              </svg>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>
<!--contact-->
<section id="contact" class="w-full pt-10 bg-zinc-950">
  <div class="flex flex-col justify-center items-center">
    <div class="w-full lg:max-w-4xl my-10 p-4 text-center border rounded-lg shadow sm:p-8 bg-gray-900 border-gray-700">
      <div class="grid sm:grid-cols-2">
        <div class="hidden md:block mx-auto my-auto">
          <%= image_tag("https://truckerjobs.s3.us-east-2.amazonaws.com/Sunset+Truck+Interior-min.jpg", alt: "View of the truck drivers seat at dusk.", class: "rounded-lg w-72 sm:w-full", loading: "lazy") %>
        </div>
        <div class="flex flex-col justify-center items-center">
          <div class="w-full lg:max-w-xl p-6 space-y-8 sm:p-8 rounded-lg lg:ml-6">
            <h2 class="flex flex-col text-2xl font-bold text-white">
              Contact Us.
            </h2>
            <div class="flex flex-col">
              <small class="text-white">
                Are you ready to jump in the driver's seat of your career? We would love to hear from you. Let's get to work on your new career today!
              </small>
              <small class="text-gray-300">
                [<span class="text-orange-300"> * </span>] indicates required
              </small>
            </div>
            <%= render "leadform" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>