config/routes.rb
Rails.application.routes.draw do
  # get 'admin/index'

  # privacy page
  get "privacy", to: "privacy#index", as: :privacy

  # Post action for the contact form in landing controller
  post "/landing/lead", to: "landing#create_lead", as: :create_lead
  # Post action for the newsletter form in landing controller
  post "/landing/newsletter", to: "landing#create_newsletter", as: :create_newsletter

  # Root route for advisor
  authenticated :admin, lambda { |a| a.role == "advisor" } do
    root to: "advisor#index", as: :advisor
  end

   # Root route for admin
   authenticated :admin, lambda { |a| a.role == "admin" } do
    root to: "admin#index", as: :admin
  end
  # Update action for update note for lead through admin dashboard
  patch "update_lead/:id", to: "admin#update_lead", as: :admin_update_lead
  # Delete action for the destroy lead
  delete "destroy_lead/:id", to: "admin#destroy_lead", as: :admin_destroy_lead
  # Delete action for the destroy newsletter
  delete "destroy_newsletter/:id", to: "admin#destroy_newsletter", as: :admin_destroy_newsletter

  # get the blog general root
  get "blog", to: "blog#index", as: :blog
  # get the single blog - show
  get "/blog/:id", to: "blog#show", as: :blog_show

  # Route for new blog
  get "new_blog", to: "advisor#new_blog", as: :advisor_new_blog
  # Route for list of blogs
  get "list_blogs", to: "advisor#list_blogs", as: :advisor_list_blogs
  # Route for edit blog
  get "edit_blog/:id", to: "advisor#edit_blog", as: :advisor_edit_blog
  # create blog through advisor dashboard
  post "create_blog", to: "advisor#create_blog", as: :advisor_create_blog
  # update blog through advisor dashboard
  patch "update_blog/:id", to: "advisor#update_blog", as: :advisor_update_blog
  # delete blog through advisor dashboard
  delete "destroy_blog/:id", to: "advisor#destroy_blog", as: :advisor_destroy_blog
  # delete cover image through advisor dashboard
  resources :blog do
    resources :cover_images, only: [:destroy], module: :blog
  end

  devise_for :admins, controllers: {
    sessions: "admin/sessions"
  }
  root 'landing#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/advisor_controller.rb
class AdvisorController < ApplicationController
  # Only allow admins to access the admin dashboard
  before_action :authenticate_staff!


  def index
    @blog = Blog.new
    @blogs = Blog.includes([:rich_text_content, cover_image_attachment: { blob: [] }]).order(created_at: :desc)
  end

  def new_blog
    @blog = Blog.new
  end

  def list_blogs
    @blogs = Blog.all.includes([:rich_text_content, cover_image_attachment: { blob: [] }])
  end

  def edit_blog
    @blog = Blog.includes([:rich_text_content, cover_image_attachment: { blob: [] }]).friendly.find(params[:id])
  end

  def create_blog
    @blog = Blog.new(blog_params)
    @blog.admin = current_admin
    if @blog.save
      @blog.update(views: @blog.views + 1)
      redirect_to advisor_list_blogs_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update_blog
    @blog = Blog.friendly.find(params[:id])
    if @blog.update(blog_params)
      redirect_to advisor_list_blogs_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy_blog
    @blog = Blog.friendly.find(params[:id])
    @blog.destroy
    redirect_to advisor_list_blogs_path
  end

  private

  def blog_params
    params.require(:blog).permit(:cover_image,
                                    :title,
                                    :content,
                                    :published_at,
                                    :seo_image,
                                    :seo_image_alt,
                                    :seo_title,
                                    :seo_description,
                                    :seo_keywords,
                                    :user_id)
  end

  # Before filter to ensure only staff (admins and advisors) can access the
  # advisor dashboard.
  #
  # If the user is not signed in or the user is not an admin or advisor, redirect
  # to the root path and alert the user that they are not authorized to access
  # the page.
  def authenticate_staff!
    if !admin_signed_in? || !["admin", "advisor"].include?(current_admin.role)
      flash[:alert] = "You are not authorized to access this page."
      redirect_to root_path
    end
  end
end

app/views/advisor/edit_blog.html.erb
<section class="bg-gray-900 mt-20 min-h-[calc(100vh-88px)]">
  <div class="py-8 sm:px-4 mx-auto max-w-screen-xl lg:py-16">
    <div class="bg-gray-800 border border-gray-700 rounded-lg lg:p-8 md:p-12 mb-8">
      <% if @blog.admin.first_name == current_admin.first_name %>
        <div class="flex flex-col justify-center items-center pb-5">
          <h1 class="m-2 text-gray-400 p-2 text-base sm:text-lg md:text-2xl">Edit Article ( no. <%= @blog.id %> )</h1>
          <!--Edit Form-->
          <%= form_with(model: @blog, url: advisor_update_blog_path) do |f| %>
            <!--Errors-->
            <% if f.object.errors.any? %>
              <div>
                <% f.object.errors.full_messages.each do |message|  %>
                  <div class="text-red-500"><%= message %></div>
                <% end %>
              </div>
            <% end %>
            <!---->
            <div class="flex flex-col my-2 lg:mx-5 md:p-4 rounded-lg md:border border-gray-700 sm:max-w-3xl">
              <div class="text-lg text-gray-800 bg-gray-500 border border-gray-700 rounded-lg mx-2 p-2">
                <div class="text-lg">
                  <%= f.label :cover_image, class: "lg:text-2xl px-2" %>
                </div>
                <div class="rounded p-2">
                  <div class="flex items-center">
                    <%= f.label :cover_image, "Select Image" %>&nbsp;
                    <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 13V8m0 8h.01M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
                      <span class="text-sm">1200 x 675 - 100kb</span>
                    </svg>
                  </div>
                  <%= f.file_field :cover_image, class: "block w-full text-sm border rounded-lg cursor-pointer text-gray-300 focus:outline-none bg-gray-600 border-gray-700" %>
                </div>
                <div class="p-2">
                  <div class="flex items-center">
                    <%= f.label :seo_image, "SEO Card Image" %>
                    <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 13V8m0 8h.01M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
                      <span class="text-sm">1200 x 675 - 100kb</span>
                    </svg>
                  </div>
                  <%= f.file_field :seo_image, class: "block w-full text-sm border rounded-lg cursor-pointer text-gray-300 focus:outline-none bg-gray-600 border-gray-700" %>
                </div>
                <div class="p-2">
                  <%= f.label :seo_image_alt, "Image text", class: "block mb-2 text-sm font-medium px-3" %>
                  <%= f.text_field :seo_image_alt, class: "border text-sm rounded-lg block w-full p-2.5 bg-gray-600 border-gray-700 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500" %>
                </div>
              </div>
              <div class="m-2">
                <%= f.label :title, class: "block mb-2 text-sm font-medium text-white px-3" %>
                <%= f.text_field :title, class: "border text-sm rounded-lg block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500" %>
              </div>
              <div class="m-2">
                <%= f.label :seo_title, class: "block mb-2 text-sm font-medium text-white px-3" %>
                <%= f.text_field :seo_title, class: "border text-sm rounded-lg block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500" %>
              </div>
              <div class="p-2">
                <div class="flex items-center mb-2">
                  <%= f.label :seo_description, class: "block text-sm font-medium text-white pe-2" %>
                  <svg class="w-5 h-5 text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 13V8m0 8h.01M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
                    <span class="text-sm text-gray-400">At least 100 characters</span>
                  </svg>
                </div>
                <%= f.text_field :seo_description, class: "border text-sm rounded-lg block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500" %>
              </div>
              <div class="flex flex-col justify-center items-center my-2 w-full lg:w-4-5 text-white bg-gray-500 py-2 sm:px-2 rounded-lg ">
                <div class="flex justify-start items-start w-full">
                  <%= f.label :content, class: "block mb-2 text-sm font-medium text-white" %>
                </div>
                <%= f.rich_text_area :content, class: "flex flex-wrap p-2.5 w-full text-sm rounded-lg border bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500 max-w-2xl" %>
              </div>
              <div class="p-2">
                <div class="flex items-center text-white">
                  <%= f.label :seo_keywords %>&nbsp;
                  <svg class="w-5 h-5 text-gray-400 me-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 13V8m0 8h.01M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
                    <span class="text-sm text-gray-400">comma seperated list</span>
                  </svg>
                </div>
                <%= f.text_field :seo_keywords, class: "border text-sm rounded-lg block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500" %>
              </div>
              <div class="flex flex-wrap justify-center items-center w-full my-4 text-white">
                <%= f.label :published_at, class: "bg-slate-600 text-slate-50 font-medium py-2 px-2 m-2 rounded-lg" %>
                <%= f.datetime_select :published_at, include_blank: true %>
              </div>
              <div class="flex justify-center items-center w-full">
                <%= f.button class: "border rounded bg-green-500 font-semibold py-2 px-4 my-2" %>
              </div>
            </div>
          <% end %>
          <%= link_to "Return Home", advisor_path, class: "border rounded bg-gray-500 text-gray-50 font-semibold py-2 px-4 my-2" %>
        </div>
      </div>
    </div>
  </section>
<% else %>
  <section class="w-full h-screen">
    <div class="flex justify-center items-center flex-col w-full h-screen">
      <h1 class="text-red-300 my-3">Oops! It appears that you are not the owner of this post.</h1>
      <%= link_to "Back to home", root_path, class: "underline text-sky-300" %>
    </div>
  </section>
<% end %>

app/views/advisor/index.html.erb
<section class="bg-gray-900 mt-14 min-h-[calc(100vh-88px)]">
  <div class="py-8 px-4 mx-auto max-w-screen-xl lg:py-16">
    <div class="bg-gray-800 border border-gray-700 rounded-lg p-8 md:p-12 mb-8">
      <h1 class="text-white text-3xl md:text-5xl font-extrabold mb-2">Welcome <%= current_admin.first_name %> <span class="hidden md:inline">to the Dashboard</span></h1>
      <p class="text-lg font-normal text-gray-400 mb-6">This dashboard is for manageing social media for the TruckerJobs4u site. You can manage blog articles and newsletters form here as well as social media content within the site.</p>
    </div>
    <div class="bg-gray-800 border border-gray-700 rounded-lg p-8 md:p-12 mb-8">
      <div class="flex">
        <span class="text-xs font-medium inline-flex items-center px-2.5 py-0.5 rounded-md bg-gray-700 text-green-300 mb-2">
          <svg class="w-3 h-3 me-1.5"" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
            <path fill-rule="evenodd" d="M6 2a2 2 0 0 0-2 2v15a3 3 0 0 0 3 3h12a1 1 0 1 0 0-2h-2v-2h2a1 1 0 0 0 1-1V4a2 2 0 0 0-2-2h-8v16h5v2H7a1 1 0 1 1 0-2h1V2H6Z" clip-rule="evenodd"/>
          </svg>
          Blog
        </span>
        <%= button_to destroy_admin_session_path, class: "text-xs font-medium inline-flex items-center px-2.5 py-0.5 rounded-md bg-gray-700 text-yellow-400 mb-2 ms-8", method: :delete do %>
          <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18Zm0 0a8.949 8.949 0 0 0 4.951-1.488A3.987 3.987 0 0 0 13 16h-2a3.987 3.987 0 0 0-3.951 3.512A8.948 8.948 0 0 0 12 21Zm3-11a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"/>
          </svg>&nbsp;
          LOG OUT
        <% end %>
      </div>
      <h2 class="text-white text-3xl font-extrabold mb-2">TruckerJobs4u Blog</h2>
      <p class="text-lg font-normal mb-4">
        <ul class="text-gray-300">
          <li>
            To create an article, click the "Create" button and complete the form.
          </li>
          <li>
            Upload a image for the article. Upload a image for the SEO card. Article image needs descriptive text.
          </li>
          <li>
            The body of the article uses a WYSIWYG editor. You can also add a cover image to the article.
          </li>
          <li>
            All SEO fields are for shareing to other sites and bots.
          </li>
          <li>
            Published at date time at the bottom of the create form:
            <ul>
              <li>
                Draft: Leave these fields empty.
              </li>
              <li>
                Published: Date and time are less than or equal to the current.
              </li>
              <li>
                Scheduled: Date and time are greater than the current.
              </li>
            </ul>
          </li>
          <li>
            To review, edit or delete an article, click the "Blogs" button. Click the card to edit. Click the trash can to delete.
          </li>
          <li>
            To review an article like a guest or user, click the "Blog" link in the navbar.
          </li>
          <li>
            The clear button will close open sections.
          </li>
        </ul>
      </p>
      <div class="flex justify-evenly items-center">
        <%= link_to advisor_list_blogs_path, class: "py-2 px-4 mt-4 rounded-lg border focus:z-10 focus:ring-4 focus:ring-gray-700 bg-gray-800 text-green-400 border-gray-600 hover:text-white hover:bg-green-700 inline-flex text-lg items-center" do %>Blogs
          <svg class="w-3.5 h-3.5 ms-2 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
          </svg>
        <% end %>
        <%= link_to advisor_new_blog_path, class: "py-2 px-4 mt-4 rounded-lg border focus:z-10 focus:ring-4 focus:ring-gray-700 bg-gray-800 text-green-400 border-gray-600 hover:text-white hover:bg-green-700 inline-flex text-lg items-center" do %>Create
          <svg class="w-3.5 h-3.5 ms-2 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
          </svg>
        <% end %>
      </div>
      <div class="flex flex-wrap justify-center items-center mt-4">
      </div>
    </div>
    <div class="bg-gray-800 border border-gray-700 rounded-lg p-8 md:p-12">
      <a href="#" class="text-xs font-medium inline-flex items-center px-2.5 py-0.5 rounded-md bg-gray-700 text-purple-400 mb-2">
        <svg class="w-3 h-3 me-1.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
          <path d="M2.038 5.61A2.01 2.01 0 0 0 2 6v12a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V6c0-.12-.01-.238-.03-.352l-.866.65-7.89 6.032a2 2 0 0 1-2.429 0L2.884 6.288l-.846-.677Z"/>
          <path d="M20.677 4.117A1.996 1.996 0 0 0 20 4H4c-.225 0-.44.037-.642.105l.758.607L12 10.742 19.9 4.7l.777-.583Z"/>
        </svg>
        Newsletter
      </a>
      <h2 class="text-white text-3xl font-extrabold mb-2">Truckerjobs4u Newsletter</h2>
      <p class="text-lg font-normal text-gray-400 mb-4">Create, update, and delete the newsletter for the site from this panel. Stages for newsletters - Draft | Scheduled | Published</p>
      <div class="flex justify-center items-center">
        <a href="#" class="py-2 px-4 rounded-lg border focus:z-10 focus:ring-4 focus:ring-gray-700 bg-gray-800 text-purple-400 border-gray-600 hover:text-white hover:bg-purple-700 inline-flex text-lg items-center">Disabled
          <svg class="w-3.5 h-3.5 ms-2 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
          </svg>
        </a>
      </div>
    </div>
  </div>
</section>
<!--New Blog-->

app/views/advisor/list_blogs.html.erb
<section class="bg-gray-900 mt-20">
  <div class="py-8 px-4 mx-auto max-w-screen-xl lg:py-16">
    <div class="bg-gray-800 border border-gray-700 rounded-lg p-8 md:p-12 mb-8">
      <div class="flex flex-wrap justify-evenly items-center w-full mt-4">
        <% @blogs.each do |blog| %>
          <div class="w-64 border rounded-lg shadow bg-gray-800 border-gray-700 m-4">
            <%= link_to advisor_edit_blog_path(blog) do %>
              <% if blog.cover_image.present? %>
                <%= image_tag blog.cover_image, class: "rounded-t-lg object-cover w-64 h-32", alt: "cover image for the article" %>
              <% end %>
            <% end %>
            <div class="p-5">
              <span class="text-xs font-medium inline-flex items-center px-2.5 py-0.5 rounded-md bg-gray-700 mb-2">
                <% if blog.status == "Draft" %>
                  <svg class="w-6 h-6 text-yellow-300" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m14.304 4.844 2.852 2.852M7 7H4a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h11a1 1 0 0 0 1-1v-4.5m2.409-9.91a2.017 2.017 0 0 1 0 2.853l-6.844 6.844L8 14l.713-3.565 6.844-6.844a2.015 2.015 0 0 1 2.852 0Z"/>
                  </svg>
                  <div class="text-yellow-300 pl-1"><%= blog.status %></div>
                <% elsif blog.status == "Scheduled" %>
                  <svg class="w-6 h-6 text-indigo-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 10h16m-8-3V4M7 7V4m10 3V4M5 20h14a1 1 0 0 0 1-1V7a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1Zm3-7h.01v.01H8V13Zm4 0h.01v.01H12V13Zm4 0h.01v.01H16V13Zm-8 4h.01v.01H8V17Zm4 0h.01v.01H12V17Zm4 0h.01v.01H16V17Z"/>
                  </svg>
                  <div class="text-indigo-400 pl-1"><%= blog.status %></div>
                <% else blog.status == "Published" %>
                  <svg class="w-6 h-6 text-green-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                    <path stroke="currentColor" stroke-width="2" d="M21 12c0 1.2-4.03 6-9 6s-9-4.8-9-6c0-1.2 4.03-6 9-6s9 4.8 9 6Z"/>
                    <path stroke="currentColor" stroke-width="2" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"/>
                  </svg>
                  <div class="text-green-400 pl-1"><%= blog.status %></div>
                <% end %>
              </span>
              <%= link_to advisor_edit_blog_path(blog) do %>
                <h5 class="mb-2 font-bold tracking-tight text-white"><%= blog.title %></h5>
              <% end %>
              <p class="mb-3 font-sm text-gray-400"><%= blog.content.to_plain_text.truncate_words(10) %></p>
              <div class="flex justify-evenly">
                <!--Edit blog-->
                <%= link_to advisor_edit_blog_path(blog), class: "inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" do %>
                  <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.779 17.779 4.36 19.918 6.5 13.5m4.279 4.279 8.364-8.643a3.027 3.027 0 0 0-2.14-5.165 3.03 3.03 0 0 0-2.14.886L6.5 13.5m4.279 4.279L6.499 13.5m2.14 2.14 6.213-6.504M12.75 7.04 17 11.28"/>
                  </svg>
                <% end %>
                <!--Delete blog-->
                <%= button_to advisor_destroy_blog_path(blog), class: "inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800", method: :delete, data: { turbo_confirm: "Are you sure?" } do %>
                  <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 7h14m-9 3v8m4-8v8M10 3h4a1 1 0 0 1 1 1v3H9V4a1 1 0 0 1 1-1ZM6 7h12v13a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V7Z"/>
                  </svg>
                <% end %>
                <!--Dashboard-->
                <%= link_to advisor_path, class: "inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" do %>
                  <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m4 12 8-8 8 8M6 10.5V19a1 1 0 0 0 1 1h3v-3a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v3h3a1 1 0 0 0 1-1v-8.5"/>
                  </svg>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>