config/routes.rb
Rails.application.routes.draw do
  # get 'admin/index'

  # privacy page
  get "privacy", to: "privacy#index", as: :privacy

  # Post action for the contact form in landing controller
  post "/landing/lead", to: "landing#create_lead", as: :create_lead
  # Post action for the newsletter form in landing controller
  post "/landing/newsletter", to: "landing#create_newsletter", as: :create_newsletter

  # Root route for advisor
  authenticated :admin, lambda { |a| a.role == "advisor" } do
    root to: "advisor#index", as: :advisor
  end

   # Root route for admin
   authenticated :admin, lambda { |a| a.role == "admin" } do
    root to: "admin#index", as: :admin
  end
  # Update action for update note for lead through admin dashboard
  patch "update_lead/:id", to: "admin#update_lead", as: :admin_update_lead
  # Delete action for the destroy lead
  delete "destroy_lead/:id", to: "admin#destroy_lead", as: :admin_destroy_lead
  # Delete action for the destroy newsletter
  delete "destroy_newsletter/:id", to: "admin#destroy_newsletter", as: :admin_destroy_newsletter

  # get the blog general root
  get "blog", to: "blog#index", as: :blog
  # get the single blog - show
  get "/blog/:id", to: "blog#show", as: :blog_show

  # Route for new blog
  get "new_blog", to: "advisor#new_blog", as: :advisor_new_blog
  # Route for list of blogs
  get "list_blogs", to: "advisor#list_blogs", as: :advisor_list_blogs
  # Route for edit blog
  get "edit_blog/:id", to: "advisor#edit_blog", as: :advisor_edit_blog
  # create blog through advisor dashboard
  post "create_blog", to: "advisor#create_blog", as: :advisor_create_blog
  # update blog through advisor dashboard
  patch "update_blog/:id", to: "advisor#update_blog", as: :advisor_update_blog
  # delete blog through advisor dashboard
  delete "destroy_blog/:id", to: "advisor#destroy_blog", as: :advisor_destroy_blog
  # delete cover image through advisor dashboard
  resources :blog do
    resources :cover_images, only: [:destroy], module: :blog
  end

  devise_for :admins, controllers: {
    sessions: "admin/sessions"
  }
  root 'landing#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/_alert.html.erb
<!--
//? this is the alert partial
-->
<span class="text-red-700 font-bold bg-red-100 rounded p-4 border-white">
  <%= alert %>
</span>

app/views/layouts/_footer.html.erb
<!-- //? Footer -->
<div class="w-full px-12 bg-black text-slate-100" >
  <nav class="flex flex-col-reverse sm:flex-row justify-evenly items-center p-4">
    <div class="flex flex-col">
      <%= link_to root_path, class: "flex max-w-64" do %>
        <%= image_tag("https://blog3169.s3.us-east-2.amazonaws.com/logo1.png", alt: "logo in a military stencile style") %>
      <% end %>
      <span class="flex"><small>TRUCKERJOBS4U.com &#169 Copywrite 2024</small></span>
    </div>
    <div class="flex flex-row justify-evenly w-full">
      <%= link_to blog_path, class: "flex items-center text-sm text-gray-400 my-4 px-4 py-3" do %>
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7h1v12a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1V5a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1h11.5M7 14h6m-6 3h6m0-10h.5m-.5 3h.5M7 7h3v3H7V7Z"/>
        </svg>
        <span class="ml-1">Blog</span>
      <% end %>
      <%= link_to root_path + "#contact", class: "flex items-center text-sm text-gray-400 my-4 px-4 py-3" do %>
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
          <path stroke="currentColor" stroke-linecap="round" stroke-width="2" d="m3.5 5.5 7.893 6.036a1 1 0 0 0 1.214 0L20.5 5.5M4 19h16a1 1 0 0 0 1-1V6a1 1 0 0 0-1-1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1Z"/>
        </svg>
        <span class="ml-1">Contact</span>
      <% end %>
    </div>
    <div>
      <% if admin_signed_in? %>
        <%= button_to destroy_admin_session_path, class: "flex items-center text-xs text-gray-400 px-4 py-3", method: :delete do %>
          <svg class="w-6 h-6" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18 17.94 6M18 18 6.06 6"/>
          </svg>
        <% end %>
      <% else %>
        <%= link_to new_admin_session_path, class: "flex items-center text-xs text-gray-400 px-4 py-3" do %>
          <svg class="w-6 h-6" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
            <path stroke="currentColor" stroke-width="2" d="M7 17v1a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-1a3 3 0 0 0-3-3h-4a3 3 0 0 0-3 3Zm8-9a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"/>
          </svg>
          <span>Admin</span>
        <% end %>
      <% end %>
    </div>
  </nav>
</div>

app/views/layouts/_navbar.html.erb
<!--The stimulus data is left in the drop down menu. Add the data controller actions-->
<!-- //? Sticky Top Navbar -->
<div class="fixed top-0 z-50 w-full" data-controller="navbar" data-action="resize@window->navbar#closeOnLargerScreen keyup@window->navbar#closeWithEscape">
  <nav class="relative flex justify-between items-center p-4 h-20 bg-zinc-800 text-gray-100">
    <div class="flex justify-evenly items-center w-full">
      <!-- //? Left section links home -->
      <div class="flex justify-center items-center ms-4">
        <%= link_to root_path do %>
          <%= image_tag("https://blog3169.s3.us-east-2.amazonaws.com/logo1.png", alt: "logo in a military stencile style", class: "w-1/2 md:w-4/6 lg:w-full") %>
        <% end %>
      </div>
      <!-- //? Right section Page Links -->
      <div class="flex flex-grow justify-end items-center me-4">
        <ul class="flex space-x-2">
          <li class="hidden md:flex"><%= link_to "Blog", blog_path %></li>
          <li class="hidden md:flex"><%= link_to "Contact", root_path + "#contact" %></li>
        </ul>
        <button class="md:hidden pb-1 w-6" role="button" aria-label="menu" data-action="click->navbar#toggle">&#9776</button>
      </div>
    </div>
  </nav>
  <!-- //? Dropdown menu - mobile -->
  <nav class="hidden bg-white absolute w-2/3 right-2 h-80 overflow-y-auto rounded-b-sm" data-navbar-target="content">
    <ul class="flex flex-col py-2 px-3">
      <%= link_to blog_path do %>
        <li class="flex border p-2 my-1 rounded-sm">Blog</li>
      <% end %>
      <%= link_to root_path + "#contact" do %>
        <li class="flex border p-2 my-1 rounded-sm">Contact</li>
      <% end %>
    </ul>
  </nav>
</div>

app/views/layouts/_notice.html.erb
<!--
//? this is the notice partial
-->
<span class="text-blue-700 font-bold bg-blue-100 rounded p-4 border-white">
  <%= alert %>
</span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>TRUCKERJOBS4U</title>
    <%= favicon_link_tag "favicon.png", rel: "icon"%>
    <%= display_meta_tags %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="bg-black">
    <header class="">
      <%= render "layouts/navbar" %>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer>
      <%= render "layouts/footer" %>
    </footer>
  </body>
</html>